### ISSUE TITLE
hardhat_api: Implement `hardhat_dropTransaction` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/anvil-zksync#148]
## **Description:**
The `hardhat_dropTransaction` endpoint needs to be implemented. The purpose of this endpoint is to remove a transaction from the mempool. [Hardhat docs for reference](https://hardhat.org/hardhat-network/docs/reference#hardhat_droptransaction), test implementations can be found [here](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-network-helpers/test/helpers/dropTransaction.ts).

```rust
// Interface in the `trait`
#[rpc(name = "hardhat_dropTransaction")]
fn drop_transaction(&self, tx_hash: H256) -> BoxFuture<Result<bool>>;

// Actual code in the `impl`
fn drop_transaction(&self, tx_hash: H256) -> BoxFuture<Result<bool>> {
    // TODO: Solution here
}
```

**JS implementation:**
```javascript
/**
 * Removes the given transaction from the mempool, if it exists.
 *
 * @param txHash Transaction hash to be removed from the mempool.
 * @returns `true` if successful, otherwise `false`.
 * @throws if the transaction was already mined.
 */
export async function dropTransaction(txHash: string): Promise<boolean> {
  const provider = await getHardhatProvider();

  assertTxHash(txHash);

  return (await provider.request({
    method: "hardhat_dropTransaction",
    params: [txHash],
  })) as boolean;
}
```

#### Expected response
Command returns proper response:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "hardhat_dropTransaction",
       "params": ["0x7fTf4C4Bf8Ecd85dEf3E1c5Df137a7512a6a57bd987f3b8e"]
     }'
```

Response:
```
{"jsonrpc":"2.0", "result":true, "id":1}
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint should return `true` if successful in removing the tx from the mempool, otherwise `false`.
    - Ensure the method executes the call reliably and efficiently.
    - Ensure errors are properly returned.

2. **Unit Tests:**
    - Write unit tests to verify the functionality of the `dropTransaction` method.
    - Ensure coverage for multiple edge-case scenarios.

3. **Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the method's purpose, return values, and any potential edge cases or error scenarios.
    - Update `SUPPORTED_APIS.md` with updated documentation and examples.
    - (Optional) Add request to `test_endpoints.http` for easier manual verification.

### **Task Checklist:**
- [ ] Implement the `dropTransaction` method.
- [ ] Write unit tests for the `dropTransaction` method.
- [ ] Add inline documentation for the `hardhat_dropTransaction` endpoint.
- [ ] Update documentation for the `hardhat_dropTransaction` endpoint in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!

**Comment by dutterbutter** [comment]
Closed in https://github.com/matter-labs/anvil-zksync/issues/417
