### ISSUE TITLE
hardhat_api: Implement `hardhat_setNextBlockBaseFeePerGas` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/anvil-zksync#150]
## **Description:**
The `hardhat_setNextBlockBaseFeePerGas` endpoint needs to be implemented. This endpoint is designed to set the base fee for the next block. Refer to the [Hardhat documentation](https://hardhat.org/hardhat-network/docs/reference#hardhat_setNextBlockBaseFeePerGas) for more details. Test implementations can be derived from the Hardhat repo [here](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-network-helpers/test/helpers/setNextBlockBaseFeePerGas.ts).

```rust
// Interface in the `trait`
#[rpc(name = "hardhat_setNextBlockBaseFeePerGas")]
fn set_next_block_base_fee_per_gas(&self, base_fee_per_gas: U256) -> BoxFuture<Result<bool>>;

// Actual code in the `impl`
fn set_next_block_base_fee_per_gas(&self, base_fee_per_gas: U256) -> BoxFuture<Result<bool>> {
    // TODO: Solution here
}
```

**JS implementation:**
```javascript
/**
 * Sets the base fee of the next block.
 *
 * @param baseFeePerGas The new base fee to use.
 */
export async function setNextBlockBaseFeePerGas(baseFeePerGas: NumberLike): Promise<void> {
  const provider = await getHardhatProvider();

  const baseFeePerGasHex = toRpcQuantity(baseFeePerGas);

  await provider.request({
    method: "hardhat_setNextBlockBaseFeePerGas",
    params: [baseFeePerGasHex],
  });
}
```

#### Expected response
Command to test the endpoint:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "hardhat_setNextBlockBaseFeePerGas",
       "params": ["0x2540be400"]
     }'
```

Response should be:
```
{"jsonrpc":"2.0", "result":true, "id":1}
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint should return `true` if successful in setting the base fee for the next block, otherwise `false`.
    - Ensure the method executes the call reliably and efficiently.
    - Errors must be handled appropriately and returned accordingly.

2. **Unit Tests:**
    - Compose unit tests to verify the `setNextBlockBaseFeePerGas` method functionality.
    - Ensure coverage for multiple edge-case scenarios.

3. **Documentation:**
    - Append inline Rust documentation (`///` comments) detailing the method's purpose, potential return values, and any significant edge cases or errors.
    - Update the documentation and examples in `SUPPORTED_APIS.md`.
    - Optionally, include this request in `test_endpoints.http` for more straightforward manual testing.

### **Task Checklist:**

- [ ]  Implement the `setNextBlockBaseFeePerGas` method.
- [ ]  Write unit tests for the `setNextBlockBaseFeePerGas` method.
- [ ]  Add inline documentation for the `hardhat_setNextBlockBaseFeePerGas` endpoint.
- [ ]  Update documentation for the hardhat_dropTransaction endpoint in SUPPORTED_APIS.md.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!

**Comment by nbaztec** [comment]
While working on this issue it came out that the bootloader would reject any transactions that have their [enforced_base_fee](https://github.com/matter-labs/era-test-node/blob/main/src/node.rs#L346) parameter set to anything other than what it expects, which is currently `250_000_000`.

![image](https://github.com/matter-labs/era-test-node/assets/1564843/f329c89a-7d4f-422e-86e8-26614523b5ed)

For the implementation WIP, see https://github.com/Moonsong-Labs/era-test-node/tree/nish-fix-150-upstream

**Comment by dutterbutter** [comment]
Closed in https://github.com/matter-labs/anvil-zksync/pull/450
