### ISSUE TITLE
[checklist]: CLI Completeness for `anvil-zksync`

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/anvil-zksync#396]
### Description
This issue tracks the implementation and parity of CLI options for `era-test-node` compared to `anvil`. The goal is to ensure consistent behaviour, usability, and feature support for developers.

**Note:** Some of these are not relevant / will intentionally behave differently due to L1 - L2 differences. 

### Goals:
1. Achieve CLI parity between `era-test-node` and `anvil`.
2. Ensure each command behaves consistently and meets developer expectations.
3. Identify and resolve deviations in functionality or usability.

### Checklist of CLI Commands:

- [x] `--accounts`
- [x] `--block-time` (See: #392 )
- [x] `--balance`
- [x] `--config-out`
- [x] `--derivation-path`
- [x] `--mnemonic`
- [x] `--mnemonic-random`
- [x] `--mnemonic-seed-unsafe`
- [x] `--port`
- [x] `--host`
- [x] `--version`
- [x] **Implement `--fork-block-number` CLI option**
- [x] **Implement `--chain-id` CLI option**
- [x] **Support for `--gas-price` (Both L1 and L2 gas price implemented)**
- [x] **Implement `--fork-url` CLI option** (partial support with `network`)
- [x] **Implement `--auto-impersonate` CLI option**
- [x] **Implement `--fork-transaction-hash` CLI option**
- [x] **Implement `--init` CLI option**
- [x] **Implement `--timestamp` CLI option**
- [x] **Implement `--no-storage-caching` CLI option** (this is `cache=none`)
- [x] **Implement `--no-mining` CLI option**
- [x] **Implement `--quiet` CLI option**
- [x] **Implement `--disable-console-log` CLI option**
- [x] **Implement `--dump-state` CLI option**
- [x] **Implement `--load-state` CLI option**
- [x] **Implement `--state` CLI option**
- [x] **Implement `--state-interval` CLI option**
- [x] **Implement `--fork-chain-id` CLI option**
- [ ] **Implement `--fork-header` CLI option**
- [x] **Implement `--order` CLI option**
- [ ] **Implement `--prune-history` CLI option**
- [ ] **Implement `--slots-in-an-epoch` CLI option**
- [ ] **Implement `--transaction-block-keeper` CLI option**
- [x] **Implement `--allow-origin` CLI option**
- [x] **Implement `--no-cors` CLI option**
- [ ] **Implement `--fork-retry-backoff` CLI option**
- [ ] **Implement `--ipc` CLI option**
- [ ] **Implement `--no-rate-limit` CLI option**
- [ ] **Implement `--retries` CLI option**
- [ ] **Implement `--timeout` CLI option**
- [ ] **Implement `--block-base-fee-per-gas` CLI option**
- [ ] **Implement `--disable-default-create2-deployer` CLI option**
- [ ] **Implement `--memory-limit` CLI option**

**Comment by dutterbutter** [comment]
Closing will re-open individual missing options on as needed basis.
